# Production stage with pre-built files
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy pre-built application
COPY ./dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
